module.exports = function(app){

    var grn_stores_contr=require('../grn_api/controller/grn_stores_contr.js')
      app.route('/stores')
        .get(grn_stores_contr.grn_stores_contr_fn)
    var grn_quality_contr=require('../grn_api/controller/grn_quality_contr.js')
      app.route('/quality')
        .get(grn_quality_contr.grn_quality_contr_fn)
    var grn_purchase_contr=require('../grn_api/controller/grn_purchase_contr.js')
      app.route('/purchase')
        .get(grn_purchase_contr.grn_purchase_contr_fn)
    var fetch_purchase_container_det_contr=require('../grn_api/controller/fetch_purchase_container_det_contr.js')
      app.route('/fetch_purchase_container_det')
        .get(fetch_purchase_container_det_contr.fetch_purchase_container_det_contr_fn)
    var save_cont_det_contr=require('../grn_api/controller/save_cont_det_contr.js')
      app.route('/save_cont_det')
        .post(save_cont_det_contr.save_cont_det_contr_fn)
    var update_cont_det_contr=require('../grn_api/controller/update_cont_det_contr.js')
      app.route('/update_cont_det')
        .post(update_cont_det_contr.update_cont_det_contr_fn)
    var update_cont_to_qual_test_contr=require('../grn_api/controller/update_cont_to_qual_test_contr.js')
      app.route('/update_cont_to_qual_test')
        .post(update_cont_to_qual_test_contr.update_cont_to_qual_test_contr_fn)
    var fetch_htno_contr=require('../grn_api/controller/fetch_htno_contr.js')
      app.route('/fetch_htno')
        .get(fetch_htno_contr.fetch_htno_contr_fn)
    var save_htno_btno_contr=require('../grn_api/controller/save_htno_btno_contr.js')
      app.route('/save_htno_btno')
        .post(save_htno_btno_contr.save_htno_btno_contr_fn)
    var fetch_inspect_size_contr=require('../grn_api/controller/fetch_inspect_size_contr.js')
      app.route('/fetch_inspection_size')
        .get(fetch_inspect_size_contr.fetch_inspect_size_contr_fn)
    var save_qlty_reg_contr=require('../grn_api/controller/save_qlty_reg_contr.js')
      app.route('/save_qlty_reg')
        .post(save_qlty_reg_contr.save_qlty_reg_contr_fn)
      }
